use std::fmt::Write;
use std::path::Path;

use crate::core::compose_parser::{
    ContainerRef, FixedContainerName, FixedHostname, FixedNameVolume,
};
use crate::core::shared_services;

/// Configuration for generating docker-compose.override.yml.
pub struct OverrideConfig<'a> {
    pub project_prefix: &'a str,
    pub services: &'a [String],
    pub shared_services_list: &'a [String],
    pub fixed_name_volumes: &'a [FixedNameVolume],
    pub fixed_container_names: &'a [FixedContainerName],
    pub fixed_hostnames: &'a [FixedHostname],
    pub container_refs: &'a [ContainerRef],
    pub version: &'a str,
    /// Whether this is a linked (non-main) worktree. When true, depends_on
    /// entries referencing shared services are removed so that profile-excluded
    /// services don't break the compose project.
    pub is_linked: bool,
    /// Per-service depends_on from the original compose file.
    pub depends_on: &'a std::collections::HashMap<String, Vec<String>>,
}

/// Generate docker-compose.override.yml content.
pub fn generate(config: &OverrideConfig<'_>) -> String {
    let project_prefix = config.project_prefix;
    let services = config.services;
    let shared_services_list = config.shared_services_list;
    let fixed_name_volumes = config.fixed_name_volumes;
    let fixed_container_names = config.fixed_container_names;
    let fixed_hostnames = config.fixed_hostnames;
    let container_refs = config.container_refs;
    let version = config.version;

    let shared_network_name = format!("{project_prefix}-shared");
    let shared_profile = shared_services::shared_profile_name();

    // Build a map: container_name -> service name (for resolving container refs)
    let name_to_service: std::collections::HashMap<&str, &str> = fixed_container_names
        .iter()
        .map(|fc| (fc.name.as_str(), fc.service.as_str()))
        .collect();

    let mut out = String::new();
    writeln!(
        out,
        "# Auto-generated by treeyard v{version}. Do not edit manually."
    )
    .unwrap();
    writeln!(out, "# Regenerate: treeyard init").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "networks:").unwrap();
    writeln!(out, "  _wt_shared:").unwrap();
    writeln!(out, "    external: true").unwrap();
    writeln!(out, "    name: {shared_network_name}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "services:").unwrap();

    for svc in services {
        let is_shared = shared_services::is_shared(svc, shared_services_list);
        writeln!(out, "  {svc}:").unwrap();

        // container_name override
        if fixed_container_names.iter().any(|fc| fc.service == *svc) {
            writeln!(
                out,
                "    container_name: ${{COMPOSE_PROJECT_NAME:-{project_prefix}}}-{svc}"
            )
            .unwrap();
        }

        // hostname override
        if fixed_hostnames.iter().any(|fh| fh.service == *svc) {
            writeln!(
                out,
                "    hostname: ${{COMPOSE_PROJECT_NAME:-{project_prefix}}}-{svc}"
            )
            .unwrap();
        }

        // container ref overrides (network_mode/pid/ipc: "container:xxx" -> "service:yyy")
        for cr in container_refs.iter().filter(|cr| cr.service == *svc) {
            if let Some(&target_svc) = name_to_service.get(cr.referenced_name.as_str()) {
                writeln!(out, "    {}: \"service:{}\"", cr.directive, target_svc).unwrap();
            }
        }

        // depends_on override: in linked worktrees, mark dependencies on
        // shared services as `required: false` so Docker Compose doesn't fail
        // when those services are excluded via profiles. (requires Compose v2.20+)
        if config.is_linked && !is_shared {
            if let Some(deps) = config.depends_on.get(svc.as_str()) {
                let shared_deps: Vec<&String> = deps
                    .iter()
                    .filter(|d| shared_services::is_shared(d, shared_services_list))
                    .collect();
                if !shared_deps.is_empty() {
                    writeln!(out, "    depends_on:").unwrap();
                    for dep in &shared_deps {
                        writeln!(out, "      {dep}:").unwrap();
                        writeln!(out, "        condition: service_started").unwrap();
                        writeln!(out, "        required: false").unwrap();
                    }
                }
            }
        }

        if is_shared {
            writeln!(out, "    profiles:").unwrap();
            writeln!(out, "      - {shared_profile}").unwrap();
            // In linked worktrees, prevent shared services from starting even
            // when explicitly named (e.g. `docker compose up db`).
            if config.is_linked {
                writeln!(out, "    deploy:").unwrap();
                writeln!(out, "      replicas: 0").unwrap();
            }
            writeln!(out, "    networks:").unwrap();
            writeln!(out, "      _wt_shared:").unwrap();
            writeln!(out, "        aliases:").unwrap();
            writeln!(out, "          - {svc}").unwrap();
        } else {
            writeln!(out, "    networks:").unwrap();
            writeln!(out, "      - _wt_shared").unwrap();
        }
    }

    if !fixed_name_volumes.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "volumes:").unwrap();
        for vol in fixed_name_volumes {
            writeln!(out, "  {}:", vol.key).unwrap();
            writeln!(
                out,
                "    name: ${{COMPOSE_PROJECT_NAME:-{project_prefix}}}_{key}",
                key = vol.key
            )
            .unwrap();
        }
    }

    out
}

/// Write override file to disk.
pub fn write_override(toplevel: &Path, content: &str) -> anyhow::Result<()> {
    let path = toplevel.join("docker-compose.override.yml");
    std::fs::write(&path, content)
        .map_err(|e| anyhow::anyhow!("failed to write {}: {e}", path.display()))
}

/// Remove override file if it exists.
pub fn remove_override(toplevel: &Path) -> anyhow::Result<()> {
    let path = toplevel.join("docker-compose.override.yml");
    if path.exists() {
        std::fs::remove_file(&path)
            .map_err(|e| anyhow::anyhow!("failed to remove {}: {e}", path.display()))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_default(
        services: &[String],
        shared: &[String],
        volumes: &[FixedNameVolume],
    ) -> String {
        let empty_deps = std::collections::HashMap::new();
        generate(&OverrideConfig {
            project_prefix: "myapp",
            services,
            shared_services_list: shared,
            fixed_name_volumes: volumes,
            fixed_container_names: &[],
            fixed_hostnames: &[],
            container_refs: &[],
            version: "0.1.0",
            is_linked: false,
            depends_on: &empty_deps,
        })
    }

    #[test]
    fn test_generate_basic() {
        let content = generate_default(&["web".into(), "api".into()], &[], &[]);
        assert!(content.contains("name: myapp-shared"));
        assert!(content.contains("  web:"));
        assert!(content.contains("  api:"));
        assert!(content.contains("- _wt_shared"));
        assert!(!content.contains("volumes:"));
        assert!(!content.contains("container_name:"));
        assert!(!content.contains("hostname:"));
    }

    #[test]
    fn test_generate_with_shared_service() {
        let content = generate_default(
            &["web".into(), "postgres".into()],
            &["postgres".into()],
            &[],
        );
        assert!(content.contains("  postgres:"));
        assert!(content.contains("profiles:"));
        assert!(content.contains("_wt_main_only"));
        assert!(content.contains("aliases:"));
        assert!(content.contains("          - postgres"));
    }

    #[test]
    fn test_generate_with_fixed_name_volumes() {
        let content = generate_default(
            &["web".into()],
            &[],
            &[
                FixedNameVolume {
                    key: "data".into(),
                    name: "my-fixed-data".into(),
                },
                FixedNameVolume {
                    key: "cache".into(),
                    name: "my-cache".into(),
                },
            ],
        );
        assert!(content.contains("volumes:"));
        assert!(content.contains("  data:"));
        assert!(content.contains("    name: ${COMPOSE_PROJECT_NAME:-myapp}_data"));
        assert!(content.contains("  cache:"));
        assert!(content.contains("    name: ${COMPOSE_PROJECT_NAME:-myapp}_cache"));
    }

    #[test]
    fn test_generate_no_volumes_when_empty() {
        let content = generate_default(&["web".into()], &[], &[]);
        assert!(!content.contains("volumes:"));
    }

    #[test]
    fn test_generate_with_container_names() {
        let content = generate(&OverrideConfig {
            project_prefix: "myapp",
            services: &["web".into(), "db".into()],
            shared_services_list: &[],
            fixed_name_volumes: &[],
            fixed_container_names: &[FixedContainerName {
                service: "web".into(),
                name: "myapp-web".into(),
            }],
            fixed_hostnames: &[],
            container_refs: &[],
            version: "0.1.0",
            is_linked: false,
            depends_on: &std::collections::HashMap::new(),
        });
        assert!(content.contains("    container_name: ${COMPOSE_PROJECT_NAME:-myapp}-web"));
        // db should NOT have container_name override
        assert!(!content.contains("container_name: ${COMPOSE_PROJECT_NAME:-myapp}-db"));
    }

    #[test]
    fn test_generate_with_hostnames() {
        let content = generate(&OverrideConfig {
            project_prefix: "myapp",
            services: &["web".into(), "db".into()],
            shared_services_list: &[],
            fixed_name_volumes: &[],
            fixed_container_names: &[],
            fixed_hostnames: &[FixedHostname {
                service: "web".into(),
                hostname: "myapp-web".into(),
            }],
            container_refs: &[],
            version: "0.1.0",
            is_linked: false,
            depends_on: &std::collections::HashMap::new(),
        });
        assert!(content.contains("    hostname: ${COMPOSE_PROJECT_NAME:-myapp}-web"));
        assert!(!content.contains("hostname: ${COMPOSE_PROJECT_NAME:-myapp}-db"));
    }

    #[test]
    fn test_generate_with_container_refs() {
        let content = generate(&OverrideConfig {
            project_prefix: "myapp",
            services: &["app".into(), "sidecar".into()],
            shared_services_list: &[],
            fixed_name_volumes: &[],
            fixed_container_names: &[FixedContainerName {
                service: "app".into(),
                name: "myapp-app".into(),
            }],
            fixed_hostnames: &[],
            container_refs: &[ContainerRef {
                service: "sidecar".into(),
                directive: "network_mode".into(),
                referenced_name: "myapp-app".into(),
            }],
            version: "0.1.0",
            is_linked: false,
            depends_on: &std::collections::HashMap::new(),
        });
        assert!(content.contains("    network_mode: \"service:app\""));
    }

    #[test]
    fn test_generate_container_ref_unknown_name_skipped() {
        let content = generate(&OverrideConfig {
            project_prefix: "myapp",
            services: &["sidecar".into()],
            shared_services_list: &[],
            fixed_name_volumes: &[],
            fixed_container_names: &[],
            fixed_hostnames: &[],
            container_refs: &[ContainerRef {
                service: "sidecar".into(),
                directive: "network_mode".into(),
                referenced_name: "unknown-container".into(),
            }],
            version: "0.1.0",
            is_linked: false,
            depends_on: &std::collections::HashMap::new(),
        });
        // Unknown container ref should not produce a rewrite
        assert!(!content.contains("network_mode:"));
    }

    #[test]
    fn test_generate_no_container_name_when_empty() {
        let content = generate_default(&["web".into()], &[], &[]);
        assert!(!content.contains("container_name:"));
        assert!(!content.contains("hostname:"));
    }
}
